### ISSUE TITLE
errors on ArchLinux and python3.9

### ISSUE THREAD

**Issue by cyberic99** [emeryberger/Hoard#58]
Hello

I am trying to use scalene on some code.

I cannot post the whole code, but here is  what it does, at least:
- creating threads, processes, using the 'forkserver' start method, on linux, and ``multiprocessing.get_context()``
- overriding ``threading.Thread.run``
- creating multiprocessing,queues

I tried to create a simple reproducer code, but I couldn't find what causes the error.

When my code creates new processes, I get these errors:
```python
Exception ignored in: <function _after_fork at 0x559984ec9880>
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 1496, in _after_fork
    thread._reset_internal_locks(False)
  File "/usr/lib/python3.9/threading.py", line 827, in _reset_internal_locks
    self._started._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 527, in _at_fork_reinit
    self._cond._at_fork_reinit()
  File "/usr/lib/python3.9/threading.py", line 253, in _at_fork_reinit
    self._lock._at_fork_reinit()
AttributeError: 'ReplacementLock' object has no attribute '_at_fork_reinit'
```
Is there a way to get more details about this exception?

Thank you

**Comment by cyberic99** [comment]
sorry, wrong project. I meant to create this issue for scalene.
